title: sudo.dog
email: wm@mengw.io
description: Sudoo Packages Index
url: https://sudo.dog
github_username: WMXPY
theme: minima
repository: SudoDotDog/Index
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - makefile
